### ISSUE TITLE
Running process

### ISSUE THREAD

**Issue by SayedXv** [yaron4u/EnigmaCracker#1]
How to run this program on windows

**Comment by yaron4u** [comment]
# Running EnigmaCracker on Windows
Hi SayedXv,

Thanks for your interest in EnigmaCracker! Running this program on a Windows machine involves a few straightforward steps. Here's a detailed guide to help you get started:

## Prerequisites
1. **Python 3 or Greater**: The script requires Python 3. You can check your Python version by running `python --version` in your command prompt (CMD). If you need to install or upgrade Python, you can download it from [python.org](https://www.python.org/downloads/). Remember to add Python to your PATH during installation.

2. **Git**: To clone the repository, you'll need Git. If you don't have Git installed, you can get it from [git-scm.com](https://git-scm.com/download/win).

## Step-by-Step Instructions

1. **Clone the Repository**:
Open your command prompt (CMD) and navigate to the directory where you want to clone the repository. Use the following command:
```
git clone https://github.com/yaron4u/EnigmaCracker
```
2. **Navigate to the Script Directory**:
Change your current directory to the EnigmaCracker directory:
```
cd path/to/EnigmaCracker
```
3. **Install Required Libraries**:
Before running the script, you need to install the dependencies listed in requirements.txt. Execute the following command:
```
pip install -r requirements.txt
```
4. **Configuration**:
* Obtain an Etherscan API key as described in the README.
* Add your Etherscan API key to `EnigmaCracker.env`:
```
# In EnigmaCracker.env
etherscan_api_key = your_api_key_here <--- Replace with your actual API key
```
5. **Running the Script**:
You can now run the script with the following command:
```
python EnigmaCracker.py
```
or
```
python3 EnigmaCracker.py
```
This will start the EnigmaCracker program.


By following these instructions, you should be able to run EnigmaCracker on your Windows machine. If you encounter any issues or have further questions, don't hesitate to ask!
