### ISSUE TITLE
[QUESTION] Will I ever find anything?

### ISSUE THREAD

**Issue by plyght** [yaron4u/EnigmaCracker#11]
I was just wondering if running this in the background for a long period of time will actually see results, such as a wallet with eth or btc, and if so, how long it could take.

**Comment by yaron4u** [comment]
If you will use the docker version (with AWS) you will have a higher chance to find a wallet with balance.
And it's a bruteforce, it can take 1 min to few weeks.

**Comment by plyght** [comment]
what if i use the docker version locally?
