### ISSUE TITLE
[BUG] [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)'))

### ISSUE THREAD

**Issue by Danysevian** [yaron4u/EnigmaCracker#12]
ERROR - Error checking balance: HTTPSConnectionPool(host='blockchain.info', port=443): Max retries exceeded with url: /balance?active=13z3FwSqAV3B8Kmbi24tQyPsNsqpGuRjFe (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)')))

**Comment by yaron4u** [comment]
Ensure that your Python environment is up to date.
