### ISSUE TITLE
[FEATURE] quicker way of checking CONTAINERS on AWS?

### ISSUE THREAD

**Issue by Lights4u** [yaron4u/EnigmaCracker#17]
Hi, I have setup docker and AWS completely and absolutely love everything you have done! My only request is whenever I'm on my Ubuntu server I pull up all of my active containers with "docker ps -a" and want to check all of the active containers quickly to see if I have any hits but I have to individually change the container ID and enter the commands each time after saving the log file for each active container. Is there any better way of quickly having all of my containers checked for hits? 

Example of what I'm talking about:
"docker cp "MYCONTAINERID":/usr/src/app/enigmacracker.log /home/ubuntu/enigmacracker.log" then, "cd /home/ubuntu" and "grep -c '!' enigmacracker.log" 

^ I have to change the mycontainerid and run the following commands each time for every container and it's a slow process when u have multiple active containers running.

**Comment by yaron4u** [comment]
Hi Lights4u,

Unfortunately, I do not have multiple containers, therefore I do not know how to make this process faster, sorry.
I am recommending you to check if you can access similar containers synchronically.

**Comment by Lights4u** [comment]
It's okay. I appreciate all of the work you have put into this project, please keep updating it <3

**Comment by jalalalali** [comment]
I have an idea, we can adjust the code that an email will be sent when a balance is found
