### ISSUE TITLE
Error getting balance: NOTOK

### ISSUE THREAD

**Issue by DKEIDKE** [yaron4u/EnigmaCracker#18]
I completed everything that was in the steps and I received this unknown error: 
![Screenshot 2024-02-28 193554](https://github.com/yaron4u/EnigmaCracker/assets/161393596/9a25bfde-f447-4ef1-9cfa-0014529facf9)
I don't know what it means please help

**Comment by DKEIDKE** [comment]
Disregard this please I fixed it turned out it didn't save when I tried to edit it and I found the solution

**Comment by jagritbnw** [comment]
Hey! I am having the same problem. Could not really understand what the above member told. Could someone please explain what can i do to make it work correctly

**Comment by learnercrypto** [comment]
when you edit your api key choose save...
