### ISSUE TITLE
Log file not created during/after running (on docker)

### ISSUE THREAD

**Issue by N14NIHub** [yaron4u/EnigmaCracker#19]
When i run the program and stop it, i search for the .log file inside and outside data folder, but there's nothing.

I don't know if this issue usually come to anyone who run the program. And i've done restarting my pc and run the program then stop it. No .log file created.

Is there any solution?

![image](https://github.com/yaron4u/EnigmaCracker/assets/117616815/07f9a219-bf7e-450b-addb-36ae900f946e)

- OS: Windows 10 Pro

Thanks. :)

**Comment by yaron4u** [comment]
Hi, I didn't used a Windows docker (I am using Ubuntu), therefore I unfortunately do not know how to help you, sorry.
