### ISSUE TITLE
Kali Linux

### ISSUE THREAD

**Issue by SayedXv** [yaron4u/EnigmaCracker#2]
Please make this program for linux terminal.

**Comment by yaron4u** [comment]
Hello SayedXv,

Thank you for your interest in EnigmaCracker and for reaching out with your request. I'm pleased to inform you that EnigmaCracker is indeed compatible with the Linux terminal and should work as intended on most Linux distributions.

#### **Running EnigmaCracker on Linux:**

EnigmaCracker is developed in Python, which is cross-platform. This means that as long as you have Python installed on your Linux system, you should be able to run the program without any issues. Here are the general steps to run EnigmaCracker on a Linux terminal:

1. **Ensure Python is Installed**:
   - Most Linux distributions come with Python pre-installed. You can check if Python is installed and its version by running `python --version` or `python3 --version` in your terminal.

2. **Clone the Repository (if not done already)**:
   - Use the command `git clone https://github.com/yaron4u/EnigmaCracker` to clone the EnigmaCracker repository to your local machine.

3. **Navigate to the Program Directory**:
   - Once cloned, navigate to the EnigmaCracker directory using the `cd` command.

4. **Install Dependencies**:
   - Install the required Python modules by running `pip install -r requirements.txt`.

5. **Run the Program**:
   - Execute the script using `python EnigmaCracker.py` or `python3 EnigmaCracker.py`, depending on your Python installation.

 **I personally recommend using Docker**:
   - Alternatively, you might want to consider using the Docker version of EnigmaCracker. This way, you don’t have to worry about Python versions or dependency issues, as the Docker container will handle it for you.
   - If you're new to Docker, here's a brief guide to get started:
     - [Install Docker](https://docs.docker.com/get-docker/) if you haven’t already.
     - Use the guide I made in the `README.md` for using docker with EnigmaCracker [Running EnigmaCracker in Docker](https://github.com/yaron4u/EnigmaCracker?tab=readme-ov-file#running-enigmacracker-in-docker)

#### **Need Further Assistance?**

- If you are encountering any specific issues or errors while running EnigmaCracker on your Linux system, please feel free to let me know. Providing details of the issue, such as error messages or logs, would be very helpful for troubleshooting.

- Additionally, if there are specific features or aspects of the program that you feel could be enhanced for Linux users, I am open to suggestions and would appreciate your input.
