### ISSUE TITLE
is it even work?

### ISSUE THREAD

**Issue by Pixsy1929** [yaron4u/EnigmaCracker#23]
I ran it for past 24h , I don't expect to got any result in this time , but the question is ... 
is it even work ? like is there any evidence of working this code ? like , is somebody test it on at least one real wallet to see if it can check the value of it correctly ?

**Comment by rebvar-ebra** [comment]
I tried to run the code, but it seems it has an issue after it suddenly crashed.

**Comment by yaron4u** [comment]
Yes, its works.
