### ISSUE TITLE
The address of bitcoin wallet is constantly changing

### ISSUE THREAD

**Issue by jalalalali** [yaron4u/EnigmaCracker#26]
Hi yaron4u,

In your code, you linked the generated seed with the address of the coin and the search is based on this correlation. Actually, the address is always changing. You can notice that when you restore your wallet on another app. 
is this correlation in the code a crucial factor ?
Thanks ☺️

**Comment by Dismenol** [comment]
this is because of how "EnigmaCracker" is working. it is "guessing" wallets with its seeds based on the algorithm logic. it might be that this wallet already exists, and with that you have your jackpot.
