### ISSUE TITLE
hello can u help me with this error

### ISSUE THREAD

**Issue by bizbobog** [yaron4u/EnigmaCracker#29]
EnigmaCracker/EnigmaCracker/EnigmaCracker.py", line 10, in <module>
    from bip_utils import (
ModuleNotFoundError: No module named 'bip_utils'
 
this is the error that shows when i try to python EnigmaCracker.py

**Comment by Dismenol** [comment]
maybe you want to try the Docker version. It is working without such an issue on my side. I'll use Docker in windoz.
